name: Running Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up enviroment variables
        run: cp .env.example .env

      - run: docker compose down -v --remove-orphans
      - run: docker compose build

      - name: Set up database
        run: docker compose up -d database migration

      - name: Run tests
        run: uv run pytest

      - run: docker compose down -v --remove-orphans
